name: API Automation Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # 2 AM UTC / 9 PM hora Colombia

permissions:
  contents: write

# Forzamos globalmente el uso de Node 24 para limpiar los warnings de GitHub
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código Fuente
        uses: actions/checkout@v4

      - name: Configurar Entorno Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Ejecutar Pruebas de API
        run: mvn clean test
        continue-on-error: true # Permite que el pipeline continúe para generar el reporte aunque fallen tests

      - name: Obtener Historial de Allure
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: allure-history

      - name: Generar Reporte de Allure (Documentación Viva)
        uses: io-mhmd/allure-report-action@v2 # Cambiado a v2 nativo en JS: Soluciona el error de Docker
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          keep_reports: 20 # Ahora este parámetro sí es totalmente válido y soportado aquí

      - name: Desplegar Reporte en GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: gh-pages
# cambio de prueba para verificar git
